# Generated by Django 4.2.2 on 2023-06-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bookingmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'permissions': [('view_address', 'Can view address'), ('create_address', 'Can create address'), ('update_address', 'Can update address'), ('delete_address', 'Can delete address')]},
        ),
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'permissions': [('create_booking', 'Can create booking'), ('update_booking', 'Can change booking'), ('delete_booking', 'Can delete booking'), ('view_booking', 'Can get booking')]},
        ),
        migrations.AlterModelOptions(
            name='mediamodel',
            options={'permissions': [('view_media', 'Can view media'), ('create_media', 'Can create media'), ('update_media', 'Can update media'), ('delete_media', 'Can delete media')]},
        ),
        migrations.AlterModelOptions(
            name='pitchmodel',
            options={'permissions': [('create_pitch', 'Can create pitch'), ('view_pitch', 'Can view pitch'), ('update_pitch', 'Can update pitch'), ('delete_pitch', 'Can delete pitch')]},
        ),
    ]
